version: '3'
services:
  mongo:
    image: "mongo:3.4"
    restart: on-failure
    ports:
      - 9010:27017
    volumes:
      - /var/webmodelica/db:/data/db
  mope-server:
    image: "thmmote/mope-server:0.6.5"
    ports:
      - 9015:3000
    volumes:
      - /var/webmodelica/data:/data
