@startuml

[JS-Client] #Green

node UserSvc #red
node AuthSvc #red

node "webmodelica-ui" {
  [Static File Server] #Green
  [JS-Client] --> [Static File Server]
}

node "webmodelica" {
  () "HTTP-API" as wm_http
  [JS-Client] --> wm_http
  [JS-Client] --> AuthSvc
  [UserService] --> UserSvc
  wm_http - [Routes] : "api calls"

  [Routes] --> [SessionService]
  [Routes] --> [SessionRegistry]
  [Routes] --> [ProjectStore]
  [Routes] --> [UserService]
  [Routes] --> [(JW-)Token Generator]

  [UserService] --> [UserDBStore]

  [SessionRegistry] --> [SessionService]

  [SessionService] --> [FileStore]
  [SessionService] --> [MopeService]
}

node "mope" {
  () "HTTP" as mope_http
  [MopeService] --> mope_http
  mope_http - [Endpoint]
}

storage RedisCache #red

database MongoDB {
  storage Project
  storage User #grey
}

database "filesystem" {
  storage ModelicaFile as fs_file
}
note left of fs_file : the directory that mope "sees"

[UserDBStore] #grey

[ProjectStore] --> Project
[UserDBStore] --> User
[UserService] --> RedisCache : cache users
[SessionService] --> RedisCache : cache completions
[FileStore] --> fs_file : write project files

[Endpoint] <-- fs_file : read project files
@enduml
