whitelisted_hostnames:
  - localhost
  - staging-webmodelica.mni.thm.de

omniauth:
  providers:
    developer:
      name: 'Developer'
      icon: 'database'
      color: '#666'
      enabled: true
    identity:
      name: 'Database login'
      color: '#00796b'
      icon: 'database'
      uid_field: 'username'
      fields:
        - email
        # - first_name
        # - last_name
        - username
      enabled: true
    # cas3:
    #   name: ''
    #   color: ''
    #   host: ''
    #   service_validate_url: ''
    #   uid_field: ''

    # google_oauth2:
    #   client_id: ''
    #   client_secret: ''

    # twitter:
    #   key: ''
    #   secret: ''

    # github:
    #   icon: ''
    #   name: ''
    #   key: ''
    #   secret: ''

    # facebook:
    #   key: ''
    #   secret: ''

    # windowslive:
    #   client_id: ''
    #   secret: ''

    # xing:
    #   consumer_key: ''
    #   consumer_secret: ''

    # linkedin:
    #   key: ''
    #   secret: ''

    # slack:
    #   key: ''
    #   secret: ''

    # steam:
    #     key: ''
