log:
  level: DEBUG

api:
  insecure: true

providers:
  docker: true

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

http:
  routers:
    redirect:
      entryPoints:
        - web
      middlewares:
        - redirect-https
        - hsts-header
      service: redirect
      rule: "HostRegexp(`{any:.*}`)"
  middlewares:
    redirect:
      redirectScheme:
        scheme: https
    hsts-header:
      headers:
        frameDeny: true
        sslRedirect: true
        stsPreload: true
        stsSeconds: 3600
  services:
    redirect:
      loadbalancer:
        servers:
          url: "http://localhost"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /ssl/cert.pem
        keyFile: /ssl/server.key
