#%RAML 1.0
---
title: Webmodelica Backend
version: v1
mediaType: application/json
baseUri: https://staging-webmodelica.mni.thm.de/api/{version}
types: !include types.raml
traits: !include traits.raml
securitySchemes:
  oauth:
    type: OAuth 2.0
    description: |
      OAuth 2.0 authentication provided by the authentication service.
      *Either* provide the `Authorization` header or the `Cookie` token.
      Both is returned when the user logged in.
    describedBy:
      headers:
        Authorization:
          description: |
            Used to send a valid OAuth 2 access token.
            Do not use in conjunction with the cookie parameter.
          type: string
          required: false
        Cookie:
          description: |
            Contains the OAuth token.
            Do not use in conjunction with the header parameter.
          type: string
          required: false
securedBy: [oauth]
/webmodelica/info:
  get:
    description: Gets application specific informations, like version, license and commit hash.
    responses:
      200:
        body:
          type: Infos
    securedBy: []
/webmodelica/projects: !include projects.raml
/webmodelica/sessions: !include sessions.raml

# POST    /users/register
# POST    /users/login
# POST    /users/refresh
