#%RAML 1.0
---
title: Webmodelica Backend
version: v1
mediaType: application/json
baseUri: https://staging-webmodelica.mni.thm.de/api/{version}/webmodelica
types: !include types.raml
traits: !include traits.raml
/info:
  get:
    description: Gets application specific informations, like version, license and commit hash.
    responses:
      200:
        body:
          type: Infos
/projects: !include projects.raml
/sessions: !include sessions.raml

# POST    /users/register
# POST    /users/login
# POST    /users/refresh
