#%RAML 1.0
---
title: Webmodelica Backend API
version: v1
mediaType: application/json
baseUri: https://staging-webmodelica.mni.thm.de/api/{version}/webmodelica
types: !include types.raml
/info:
  get:
    description: Gets application specific informations, like version, license and commit hash.
    responses:
      200:
        body:
          type: Infos
          example: !include examples/webmodelica.controllers.Infos-example.json
/projects:
  get:
    description: Get all projects for the current user.
    responses:
      200:
        body:
          type: JSProject[]
          example: !include examples/webmodelica.models.JSProject-example.json
  post:
    description: Creates a new (private) project for the current user.
    body:
      type: createProject
      example: !include examples/webmodelica.models.ProjectRequest-example.json
  /{projectId}:
    get:
      description: Get the project with id={projectId}.
      responses:
        200:
          body:
            type: JSProject
            example: !include examples/webmodelica.models.JSProject-example.json
    delete:
      description: Delete the project with id={projectId}.
      responses:
        204:
          description: Project deleted. Note that this is returned even if the project doesn't exist.
    /copy:
      post:
        description: Copies a project.
        body:
          type: object
          properties:
            name:
              type: string
              required: false
        responses:
          200:
            body:
              type: JSProject
              example: !include examples/webmodelica.models.JSProject-example.json
    /visibility:
      put:
        description: Updates the visibility of the project.
        body:
          type: object
          properties:
            visibility:
              description: the visibility of the project, either 'public' or 'private'.
              type: string
        responses:
          200:
            body:
              type: JSProject
              example: !include examples/webmodelica.models.JSProject-example.json
          400:
            description: if provided visibility isn't allowed.
    /files:
      /download:
        get:
          description: Returns a zip archive with the project files.
          responses:
            200:
              application/zip:
                description: the zip archive
      /{path}:
        get:
          description: Get the file with the given {path}.
          responses:
            200:
              body:
                type: ModelicaFile
                example: !include examples/webmodelica.models.ModelicaFile-example.json
            404:
              description: if {path} not found.
    /sessions/new:
      post:
        description: creates a new session based on this project.
        responses:
            200:
              body:
                type: JSSession
                example: !include examples/webmodelica.models.JSSession-example.json

# DELETE  /sessions/:sessionId
# POST    /sessions/:sessionId/files/update
# POST    /sessions/:sessionId/files/upload
# DELETE  /sessions/:sessionId/files/:path
# PUT     /sessions/:sessionId/files/rename
# POST    /sessions/:sessionId/compile
# POST    /sessions/:sessionId/complete
# POST    /sessions/:sessionId/simulate
# GET     /sessions/:sessionId/simulate
# POST    /users/register
# POST    /users/login
# POST    /users/refresh
