#%RAML 1.0
---
    
Infos:
  type: !include schemas/webmodelica.controllers.Infos-schema.json
  example: !include examples/webmodelica.controllers.Infos-example.json
AuthUser:
  type: !include schemas/webmodelica.models.AuthUser-schema.json
  example: !include examples/webmodelica.models.AuthUser-example.json
ProjectRequest:
  type: !include schemas/webmodelica.models.ProjectRequest-schema.json
  example: !include examples/webmodelica.models.ProjectRequest-example.json
JSProject:
  type: !include schemas/webmodelica.models.JSProject-schema.json
  example: !include examples/webmodelica.models.JSProject-example.json
JSSession:
  type: !include schemas/webmodelica.models.JSSession-schema.json
  example: !include examples/webmodelica.models.JSSession-example.json
ModelicaPath:
  type: !include schemas/webmodelica.models.ModelicaPath-schema.json
  example: !include examples/webmodelica.models.ModelicaPath-example.json
ModelicaFile:
  type: !include schemas/webmodelica.models.ModelicaFile-schema.json
  example: !include examples/webmodelica.models.ModelicaFile-example.json
FilePosition:
  type: !include schemas/webmodelica.models.mope.FilePosition-schema.json
  example: !include examples/webmodelica.models.mope.FilePosition-example.json
FilePath:
  type: !include schemas/webmodelica.models.mope.FilePath-schema.json
  example: !include examples/webmodelica.models.mope.FilePath-example.json
Suggestion:
  type: !include schemas/webmodelica.models.mope.responses.Suggestion-schema.json
  example: !include examples/webmodelica.models.mope.responses.Suggestion-example.json
CompilerError:
  type: !include schemas/webmodelica.models.mope.responses.CompilerError-schema.json
  example: !include examples/webmodelica.models.mope.responses.CompilerError-example.json
Complete:
  type: !include schemas/webmodelica.models.mope.requests.Complete-schema.json
  example: !include examples/webmodelica.models.mope.requests.Complete-example.json
SimulationResult:
  type: !include schemas/webmodelica.models.mope.responses.SimulationResult-schema.json

TableFormat:
  type: !include schemas/webmodelica.controllers.TableFormat-schema.json

FileOrPath:
  type: !include schemas/FileOrPath-schema.json

SimulationResultOrTableFormat:
  type: !include schemas/SimulationResultOrTableFormat-schema.json
