project: !include schemas/webmodelica.models.JSProject.json
createProject: !include schemas/webmodelica.models.ProjectRequest.json
infos: !include schemas/webmodelica.controllers.Infos.json
user: !include schemas/webmodelica.models.AuthUser.json
session: !include schemas/webmodelica.models.JSSession.json
file: !include schemas/webmodelica.models.ModelicaFile.json
# filePath: !includeb
