= Webmodelica Developer Documentation
:author: Nicola Justus
:icons: font
:toc: left
:imagesdir: images
:sectnums:
:source-highlighter: rouge
:stylesheet: foundation-potion.css
:nofooter:
:docinfo:

== Setup

Setting up a development machine requires a few steps:

* first install the required software:
  - docker and docker-compose
  - node and npm
  - sbt
  - a TypeScript editor (e.g.: VS Code)
  - a Scala editor (e.g.: VS Code or IntelliJ Idea)
* setup authentication providers as described in the repositories https://github.com/THM-MoTE/webmodelica#docker[README]:
  `cp deployment/config/auth-svc.settings.sample.yml deployment/config/auth-svc.settings.yml`
* start the development compose file in a separate terminal: `docker-compose -f deployment/docker-compose.yml up`
* fire up the sbt console: `sbt`
* inside sbt, run the application: `run`
* start the frontend dev server in a separate terminal: `cd ui && npm start`

Now you can access the application at `http://localhost:9000`.

WARNING: in development mode, the traefik proxy - that is available at `localhost:9000` -
  assumes that the backend is running at `localhost:8888` and the ui is running at `localhost:3000`.
  Because traefik is running inside of docker, the proxy routes to the docker host address at `172.17.0.1`.
  If your docker daemon's host address is not `172.17.0.1`, update the config in
  link:../deployment/config/traefik-dev.toml[traefik-dev.toml].
  Update the URL of `backends.webmodelica-backend-dev.servers.s0` and `backends.webmodelica-ui-dev.servers.s0`.
  That's the case when running docker on OSX.
  PLEASE DON'T COMMIT THIS CHANGE!

== Release new versions

WARNING: before you can publish a new release, you need a DockerHub account and write access to the https://hub.docker.com/u/thmmote[thmmote] group!

There is a script (`project/release.sh`) available for generating new releases.
This script does the following:

. write the new version into `project/version.txt`. sbt reads this file to set the version.
. fully compiles and packages the backend through sbt into `target/universal/webmodelica-<new version>.txz`
. fully builds the frontend into `ui/build`
. commits and tags the `version.txt` file
. builds both docker images for backend and frontend
. replaces the versions in `deployment/docker-compose.prod.yml`
. pushes the commits and tags onto GitHub
. pushes the images onto DockerHub

Usage:
[source, sh]
----
$ bash scripts/release.sh <new version number>
$ bash scripts/release.sh 0.6.5
----

include::sections/dependencies.adoc[]

include::sections/architecture.adoc[]

include::sections/deployment.adoc[]

include::sections/authentication.adoc[]

include::sections/domain_model.adoc[]

include::sections/conversions.adoc[]

== TBD
* project path mapper
* authentication flow
* redux, flux
* display UI marked components
