version: '3'
services:
  backend:
    image: "thmmote/webmodelica:0.7.0"
    restart: unless-stopped
    ports:
      - 9002:3000
    labels:
      - "traefik.frontend.rule=PathPrefix:/api/v{[0-9]+}/webmodelica"
      - "traefik.backend=webmodelica-backend"
      - "traefik.port=3000"
      - "de.thm.webmodelica.name=webmodelica-backend"
    depends_on:
      - cache
      - mongo
      - auth-svc
    environment:
      - AUTH_PUBLIC_KEY=/opt/auth-key.pub
    volumes:
      - ../conf/auth-svc-key.pub:/opt/auth-key.pub
      - webmodelica_data:/data
  ui:
    image: "thmmote/webmodelica-ui:0.7.0"
    restart: unless-stopped
    ports:
      - 9003:3000
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.backend=webmodelica-ui"
      - "traefik.port=3000"
      - "de.thm.webmodelica.name=webmodelica-frontend"
  traefik:
    restart: unless-stopped
  mongo:
    restart: unless-stopped
  cache:
    restart: unless-stopped
  auth-svc:
    restart: unless-stopped
  user-svc:
    restart: unless-stopped
  mope:
    restart: unless-stopped
    volumes:
      - webmodelica_data:/home/openmodelica/data
      - ./mope.conf:/home/openmodelica/.config/mope/mope.conf
#      - ../moie-server/target/scala-2.12/mope-server-0.6.5.jar:/opt/mope-server.jar
