version: '3'
services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "9000:80"     # The HTTP port
      - "9080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./config/traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "de.thm.webmodelica.name=traefik-proxy"
    restart: on-failure
  mongo:
    image: "mongo:3.4"
    restart: on-failure
    volumes:
      - webmodelica_db:/data/db
    ports:
      - 9010:27017
    labels:
      - "de.thm.webmodelica.name=mongodb"
      - "traefik.enable=false"
  cache:
    image: "redis:5.0.4-alpine"
    restart: on-failure
    ports:
      - 9011:6379
    volumes:
      - redis_cache:/data
    labels:
      - "de.thm.webmodelica.name=redis-cache"
      - "traefik.enable=false"
  mope:
    image: "thmmote/mope-server:0.6.9"
    restart: on-failure
    user: openmodelica:openmodelica
    ports:
      - 9015:3000
    labels:
      - "de.thm.webmodelica.name=mope-server"
    volumes:
      - ../private/data:/home/openmodelica/data
      - ./config/mope.conf:/home/openmodelica/.config/mope/mope.conf
  user-svc:
    image: thmmote/webmodelica-user-svc:0.1.2
    restart: on-failure
    ports:
      - 9012:3000
    environment:
      - RAILS_MASTER_KEY=ee58f8f3dfb3b3fd40391087bfd38c4e
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    labels:
      - "traefik.frontend.rule=PathPrefix:/api/v{[0-9]+}/users"
      - "traefik.backend=webmodelica-user-svc"
      - "traefik.port=3000"
      - "de.thm.webmodelica.name=webmodelica-user-svc"
  auth-svc:
    image: thmmote/webmodelica-auth-svc:0.0.2
    restart: on-failure
    ports:
      - 9013:3000
    environment:
      - RAILS_MASTER_KEY=f84a1e93cf144b98ded39b233d03b60f
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - USER_SERVICE_HOST=user-svc
      - USER_SERVICE_PORT=3000
      - LOGIN_REDIRECT_URI=http://localhost:3000/
    volumes:
      - ./config/auth-svc.settings.yml:/application/config/settings.yml
    labels:
      - "traefik.frontend.rule=PathPrefix:/api/v{[0-9]+}/auths"
      - "traefik.backend=webmodelica-auth-svc"
      - "traefik.port=3000"
      - "de.thm.webmodelica.name=webmodelica-auth-svc"
  backend:
    image: "thmmote/webmodelica:0.7.0-auth"
    ports:
      - 9002:3000
    labels:
      # - "traefik.frontend.rule=PathPrefix:/api/v{[0-9]+}/webmodelica"
      - "traefik.frontend.rule=PathPrefix:/api/v{[0-9]+}"
      - "traefik.backend=webmodelica-backend"
      - "traefik.port=3000"
      - "de.thm.webmodelica.name=webmodelica-backend"
    environment:
      - AUTH_PUBLIC_KEY=/opt/auth-key.pub
    volumes:
      - ../conf/auth-svc-key.pub:/opt/auth-key.pub
      - webmodelica_data:/data

volumes:
  webmodelica_data:
  webmodelica_db:
  redis_cache:
  auth_db:
