version: '3'
services:
  mongo:
    image: "mongo:3.4"
    restart: on-failure
    volumes:
      - webmodelica_db:/data/db
    ports:
      - 9010:27017
    labels:
      - "de.thm.webmodelica.name=mongodb"
  cache:
    image: "redis:5.0.4-alpine"
    restart: on-failure
    ports:
      - 9011:5000
    volumes:
      - redis_cache:/data
    labels:
      - "de.thm.webmodelica.name=redis-cache"
  mope:
    image: "thmmote/mope-server:0.6.9"
    restart: on-failure
    user: openmodelica:openmodelica
    ports:
      - 9015:3000
    labels:
      - "de.thm.webmodelica.name=mope-server"
    volumes:
      - ../private/data:/home/openmodelica/data
      - ./mope.conf:/home/openmodelica/.config/mope/mope.conf
#      - ../moie-server/target/scala-2.12/mope-server-0.6.5.jar:/opt/mope-server.jar

volumes:
  webmodelica_data:
  webmodelica_db:
  redis_cache:
