version: '3'
services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  backend:
    image: "thmmote/webmodelica:0.6.8"
    restart: on-failure
    ports:
      - 9002:3000
    labels:
      - "traefik.frontend.rule=PathPrefix:/api"
      - "traefik.backend=webmodelica-backend"
      - "traefik.port=3000"
    volumes:
      - webmodelica_data:/data
  ui:
    image: "thmmote/webmodelica-ui:0.6.8"
    restart: on-failure
    ports:
      - 9003:3000
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.backend=webmodelica-ui"
      - "traefik.port=3000"
  mope:
    image: "thmmote/mope-server:0.6.9"
    restart: on-failure
    user: openmodelica:openmodelica
    volumes:
      - webmodelica_data:/home/openmodelica/data
      - ./mope.conf:/home/openmodelica/.config/mope/mope.conf
#      - ../moie-server/target/scala-2.12/mope-server-0.6.5.jar:/opt/mope-server.jar
