version: '3'
services:
  backend:
    image: "thmmote/webmodelica:0.7.2"
    restart: unless-stopped
    ports:
      - 9002:3000
    labels:
      - "traefik.frontend.rule=PathPrefix:/api/v{[0-9]+}/webmodelica"
      - "traefik.backend=webmodelica-backend"
      - "traefik.port=3000"
      - "de.thm.webmodelica.name=webmodelica-backend"
    depends_on:
      - cache
      - mongo
      - auth-svc
    environment:
      - AUTH_PUBLIC_KEY=/opt/auth-key.pub
    volumes:
      - ../conf/auth-svc-key.pub:/opt/auth-key.pub
      - webmodelica_data:/data
  ui:
    image: "thmmote/webmodelica-ui:0.7.2"
    restart: unless-stopped
    ports:
      - 9003:3000
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.backend=webmodelica-ui"
      - "traefik.port=3000"
      - "de.thm.webmodelica.name=webmodelica-frontend"
  traefik:
    restart: unless-stopped
    ports:
      - "80:80"     # The HTTP port
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./config/traefik.toml:/etc/traefik/traefik.toml
      - ./config/traefik-prod.toml:/etc/traefik/traefik-prod.toml
      - ./config/traefik-dev.toml:/tmp
  mongo:
    restart: unless-stopped
  cache:
    restart: unless-stopped
  auth-svc:
    restart: unless-stopped
  user-svc:
    restart: unless-stopped
  mope:
    restart: unless-stopped
    volumes:
      - webmodelica_data:/home/openmodelica/data
      - ./config/mope.conf:/home/openmodelica/.config/mope/mope.conf
#      - ../moie-server/target/scala-2.12/mope-server-0.6.5.jar:/opt/mope-server.jar
