version: '3'
services:
  mongo:
    image: "mongo:3.4"
    restart: on-failure
    volumes:
      - webmodelica_db:/data/db
    ports:
      - 9010:27017
    labels:
      - "de.thm.webmodelica.name=mongodb"
  cache:
    image: "redis:5.0.4-alpine"
    restart: on-failure
    ports:
      - 9011:6379
    volumes:
      - redis_cache:/data
    labels:
      - "de.thm.webmodelica.name=redis-cache"
  mope:
    image: "thmmote/mope-server:0.6.9"
    restart: on-failure
    user: openmodelica:openmodelica
    ports:
      - 9015:3000
    labels:
      - "de.thm.webmodelica.name=mope-server"
    volumes:
      - ../private/data:/home/openmodelica/data
      - ./mope.conf:/home/openmodelica/.config/mope/mope.conf
#      - ../moie-server/target/scala-2.12/mope-server-0.6.5.jar:/opt/mope-server.jar
  user-svc:
    image: thmmote/webmodelica-user-svc:0.1
    restart: on-failure
    ports:
      - 9012:3000
    environment:
      - RAILS_ENV=webmodelica
      - RAILS_MASTER_KEY=ee58f8f3dfb3b3fd40391087bfd38c4e
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
  auth-db:
    image: postgres:11-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=webmodelica
      - POSTGRES_PASSWORD=au6ureeZi8uang3Oonah8zu
    volumes:
      - auth_db:/var/lib/postgresql/data
  auth-svc:
    image: thmmsgroup3/service.auth:latest
    restart: on-failure
    ports:
      - 9013:3000
    environment:
      - RAILS_MASTER_KEY=f84a1e93cf144b98ded39b233d03b60f
      - USER_SERVICE_HOST=user-svc
      - USER_SERVICE_PORT=3000
      - POSTGRESQL_HOST=auth-db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=webmodelica
      - POSTGRESQL_PASSWORD=au6ureeZi8uang3Oonah8zu

volumes:
  webmodelica_data:
  webmodelica_db:
  redis_cache:
  auth_db:
