version: '3'
services:
  admin_mongo:
    image: "mongo-express"
    restart: on-failure
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_SITE_BASEURL=/mongo/
      - VCAP_APP_HOST=0.0.0.0
    labels:
      - "traefik.frontend.rule=PathPrefix:/mongo"
