version: '3'
services:
  traefik:
    image: "traefik:latest"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entryPoints.web.address=:80"
    ports:
      - "9000:80"     # The HTTP port
      - "9080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    labels:
      - "de.thm.webmodelica.name=traefik-proxy"
    restart: on-failure
  mongo:
    image: "mongo:3.4"
    restart: on-failure
    volumes:
      - webmodelica_db:/data/db
    labels:
      - "de.thm.webmodelica.name=mongodb"
      - "traefik.enable=false"
  cache:
    image: "redis:5.0.4-alpine"
    restart: on-failure
    volumes:
      - redis_cache:/data
    labels:
      - "de.thm.webmodelica.name=redis-cache"
      - "traefik.enable=false"
  mope:
    image: "thmmote/mope-server:0.7.1"
    restart: on-failure
    user: openmodelica:openmodelica
    labels:
      - "de.thm.webmodelica.name=mope-server"
      - "traefik.enable=false"
    volumes:
      - ../private/data:/home/openmodelica/data
      - ./config/mope.conf:/home/openmodelica/.config/mope/mope.conf
  user-svc:
    image: hobbypunk90/mt-services-user:fa26b3d
    restart: on-failure
    # ports:
    #   - 9012:3000
    depends_on:
      - mongo
    environment:
      - RAILS_MASTER_KEY=ee58f8f3dfb3b3fd40391087bfd38c4e
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./config/user-svc.settings.yml:/config.yml
    labels:
      - "traefik.http.routers.user-svc.rule=PathPrefix(`/api/v{[0-9]+}/users`)"
      - "de.thm.webmodelica.name=webmodelica-user-svc"
  auth-svc:
    image: hobbypunk90/mt-services-auth:0.0.3
    restart: on-failure
    depends_on:
      - mongo
      - user-svc
    environment:
      - RAILS_MASTER_KEY=f84a1e93cf144b98ded39b233d03b60f
      - RAILS_ENV=development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - USER_SERVICE_HOST=user-svc
      - USER_SERVICE_PORT=3000
      - USER_SERVICE_PROTOCOL=http
      #- LOGIN_REDIRECT_URI=http://localhost:9000/
    volumes:
      - ./config/auth-svc.settings.yml:/config.yml
    labels:
      - "traefik.http.routers.auth-svc.rule=PathPrefix(`/api/v{[0-9]+}/auths`)"
      - "de.thm.webmodelica.name=webmodelica-auth-svc"
volumes:
  webmodelica_data:
  webmodelica_db:
  redis_cache:
  auth_db:

# api/v1/auths/identity/register
