version: '3'
services:
  mongo:
    image: "mongo:3.4"
    restart: on-failure
    ports:
      - 9010:27017
    volumes:
      - webmodelica_db:/data/db
  mope:
    image: "thmmote/mope-server:0.6.5-bugfix"
    user: openmodelica:openmodelica
    ports:
      - 9015:3000
    volumes:
      - webmodelica_data:/home/openmodelica/data
      - ./mope.conf:/home/openmodelica/.config/mope/mope.conf
#      - ../moie-server/target/scala-2.12/mope-server-0.6.5.jar:/opt/mope-server.jar

volumes:
  webmodelica_data:
  webmodelica_db: