version: '3'
services:
  backend:
    image: "thmmote/webmodelica:0.8.1"
    restart: unless-stopped
    labels:
      - "de.thm.webmodelica.name=webmodelica-backend"
      - "traefik.http.routers.webmodelica.rule=PathPrefix(`/api/v{[0-9]+}/webmodelica`)"
      - "traefik.http.routers.webmodelica.tls"
    depends_on:
      - cache
      - mongo
      - auth-svc
    environment:
      - AUTH_PUBLIC_KEY=/opt/auth-key.pub
    volumes:
      - ../conf/auth-svc-key.pub:/opt/auth-key.pub
      - webmodelica_data:/data
  ui:
    image: "thmmote/webmodelica-ui:0.8.1"
    restart: unless-stopped
    labels:
      - "de.thm.webmodelica.name=webmodelica-frontend"
      - "traefik.http.routers.webmodelica-ui.rule=PathPrefix(`/`)"
      - "traefik.http.routers.webmodelica-ui.tls"
  traefik:
    restart: unless-stopped
    ports:
      - "80:80"     # The HTTP port
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./config/traefik-prod.yaml:/etc/traefik/traefik.yaml
      # - /etc/ssl/private:/ssl
      - ../private/ssl:/ssl
  mongo:
    restart: unless-stopped
  cache:
    restart: unless-stopped
  auth-svc:
    restart: unless-stopped
    labels:
      - "traefik.http.routers.auth-svc.tls"
  user-svc:
    restart: unless-stopped
    labels:
      - "traefik.http.routers.user-svc.tls"
  mope:
    restart: unless-stopped
    volumes:
      - webmodelica_data:/home/openmodelica/data
      - ./config/mope.conf:/home/openmodelica/.config/mope/mope.conf
#      - ../moie-server/target/scala-2.12/mope-server-0.6.5.jar:/opt/mope-server.jar
