== Dependencies

Webmodelica is based on the following tools and libraries:

=== Backend
* Twitter's Finatra
  a library for HTTP-Backends.
* Twitter's Finagle
  a library for distributed systems.
  Its the middleware that drives Finatra and enables protocol-agnostic
  RPC-Calls based on Future's.
  Each RPC-Call is a function: `A => Future[B]`.
* Twitter's Featherbed
  a HTTP-Client library based on finagle.
  It enables describing HTTP-calls with minimal overhead.
  The communication with MoPE uses Featherbed for communicating with the HTTP-API.
* pureconfig
  a wrapper around Typesafe's Config library.
  It parses the config file and generates a Scala case class.
  In our case it reads `conf/webmodelica.conf` and creates an instance of `webmodelica.config.WMConfig`.
* scala cats
  functional programming library for scala.
  Its main purpose is for nested Monad transfomers, for example: `Future[Option[A]]`.
* chimney
  a library for converting objects between case classes.
  This allows easy conversion between case classes with similar shapes.
* ScalaTest
  testing library for scala based on Behaviour driven Development.
  Its awesome ;).
* sbt
  the scala build tool.


=== Frontend
* React.js the SPA framework.
* Typescript a typed JS.
* ramda.js a js library with functional utilities for lists, objects and maps.
* Gitub's octicons
  icon library similar to font awesome but from GitHub.
* redux, react-redux
* bootstrap
* Microsoft's monaco editor
