== Setup

Setting up a development machine requires a few steps:

* first install the required software:
  - docker and docker-compose
  - node and npm
  - sbt
  - a TypeScript editor (e.g.: VS Code)
  - a Scala editor (e.g.: VS Code or IntelliJ Idea)
* start the development compose file in a separate terminal: `docker-compose -f deployment/docker-compose.yml`
* fire up the sbt console: `sbt`
* inside sbt, run the application: `run`
* start the frontend dev server in a separate terminal: `cd ui && npm start`

Now you can access the application at `http://localhost:9000`.

WARNING: in development mode, the traefik proxy - that is available at `localhost:9000` -
  assumes that the backend is running at `localhost:8888` and the ui is running at `localhost:3000`.
  Because traefik is running inside of docker, the proxy routes to the docker host address at `172.17.0.1`.
  If your docker daemon's host address is not `172.17.0.1`, update the config in
  link:../deployment/config/traefik-dev.toml[traefik-dev.toml].
  Update the URL of `backends.webmodelica-backend-dev.servers.s0` and `backends.webmodelica-ui-dev.servers.s0`.
  That's the case when running docker on OSX.
  PLEASE DON'T COMMIT THIS CHANGE!

== Release new versions

WARNING: before you can publish a new release, you need a DockerHub account and write access to the https://hub.docker.com/u/thmmote[thmmote] group!

There is a script (`project/release.sh`) available for generating new releases.
This script does the following:

. write the new version into `project/version.txt`. sbt reads this file to set the version.
. fully compiles and packages the backend through sbt into `target/universal/webmodelica-<new version>.txz`
. fully builds the frontend into `ui/build`
. commits and tags the `version.txt` file
. builds both docker images for backend and frontend
. replaces the versions in `deployment/docker-compose.prod.yml`
. pushes the commits and tags onto GitHub
. pushes the images onto DockerHub

Usage:
[source, sh]
----
$ bash scripts/release.sh <new version number>
$ bash scripts/release.sh 0.6.5
----

== Libraries

Webmodelica is based on the following tools and libraries:

=== Backend
* Twitter's https://twitter.github.io/finatra/user-guide/[Finatra]
  a library for HTTP-Backends.

* Twitter's https://twitter.github.io/finagle/[Finagle]
  a library for distributed systems.
  Its the middleware that drives Finatra and enables protocol-agnostic
  RPC-Calls based on Future's.
  Each RPC-Call is a function: `A => Future[B]`.

* Twitter's https://finagle.github.io/featherbed/doc/02-basic-usage.html[Featherbed]
  a HTTP-Client library based on finagle.
  It enables describing HTTP-calls with minimal overhead.
  The communication with MoPE uses Featherbed for communicating with the HTTP-API.

* https://pureconfig.github.io/[pureconfig]
  a wrapper around Typesafe's Config library.
  It parses a config file and generates a Scala case class.
  In our case it reads `conf/webmodelica.conf` and creates an instance of `webmodelica.config.WMConfig`.

* https://typelevel.org/cats/[scala cats]
  functional programming library for scala.
  Its main purpose is for nested Monad transfomers, for example: `Future[Option[A]]`.

* https://scalalandio.github.io/chimney/[chimney]
  a library for converting objects between case classes.
  This allows easy conversion between case classes with similar shapes.

* http://www.scalatest.org/at_a_glance/FlatSpec[ScalaTest]
  testing library for scala based on Behaviour driven Development.
  Its awesome ;).

* https://www.scala-sbt.org/1.x/docs/index.html[sbt]
  the scala build tool.


=== Frontend
* https://reactjs.org/[React.js]
  the SPA framework.
* https://www.typescriptlang.org/[TypeScript]
* https://ramdajs.com/docs/[ramda.js]
  a js library with functional utilities for lists, objects and maps.
* Gitub's https://octicons.github.com/[octicons]
  icon library similar to font awesome but from GitHub.
  redux, react-redux
* https://getbootstrap.com/[bootstrap]
* https://react-bootstrap.github.io/[react-bootstrap]
  a component library for react based on bootstrap.
* Microsoft's https://microsoft.github.io/monaco-editor/playground.html[Monaco Editor]
  the code editor that powers VS Code. We are using it for editing Modelica code.
